Revert "Enable /configs/diff to diff two configs by id"
[#150705441](https://www.pivotaltracker.com/story/show/150705441)

This reverts commit ca56d6e99d5f27adb8dcc7a4ff7370442d28673a.

It was causing failures in integration tests for bosh and bosh-cli pipelines
since it seems like the diff-config command is not yet ready. Once the command
is ready, it should be okay to restore.

The failure was:

  1) cli configs can diff configs diffs two configs
     Failure/Error: expect(bosh_runner.run("diff-config #{from} #{to}")).to include('- vm_types:', '+ releases:', 'Succeeded')
     RuntimeError:
       ERROR: bosh  --tty --client=test --client-secret=test -n -e https://127.0.0.1:61604 --config /tmp/build/543eca54/bosh-src/src/tmp/integration-tests-workspace/pid-11909/client-sandbox/bosh_config.yml --ca-cert /tmp/build/543eca54/bosh-src/src/bosh-dev/assets/sandbox/ca/certs/rootCA.pem --sha2 diff-config 1 2 failed with output:
       Unknown command `diff-config', did you mean `cpi-config'?

       Exit code 1
     # ./spec/support/bosh_go_cli_runner.rb:93:in `run_in_dir'
     # ./spec/support/bosh_go_cli_runner.rb:18:in `run'
     # ./spec/gocli/integration/cli_configs_spec.rb:90:in `block (3 levels) in <top (required)>'

Sample build failures were:

 * https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh/jobs/integration-db-tls-mysql/builds/30
 * https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:cli/jobs/integration-2.3-postgres-gocli/builds/1159

Signed-off-by: Tom Viehman <tviehman@pivotal.io>