CI: stop installing clang on integration image
After switching to noble the clang installed on the container image
began failing to compile nginx:

```
/usr/bin/clang -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wconditional-uninitialized -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/event/quic -I src/os/unix -I ../../pcre-8.45 -I objs -I src/http -I src/http/modules \
	-o objs/addon/src/ngx_http_headers_more_headers_in.o \
	../../headers-more-nginx-module-0.34/src/ngx_http_headers_more_headers_in.c
../../headers-more-nginx-module-0.34/src/ngx_http_headers_more_headers_in.c:766:24: error: variable 'nelts' set but not used [-Werror,-Wunused-but-set-variable]
  766 |     int                nelts;
      |                        ^
1 error generated.
make[1]: *** [objs/Makefile:1300: objs/addon/src/ngx_http_headers_more_headers_in.o] Error 1
make[1]: Leaving directory '/tmp/build/04d13fd0/bosh/src/tmp/nginx-work/nginx-src/nginx-1.29.3'
make: *** [Makefile:10: build] Error 2
rake aborted!
```
Ex: https://bosh.ci.cloudfoundry.org/teams/main/pipelines/bosh-director/jobs/integration-postgres/builds/820#L6915ad9f:1953