Fix failing integration tests.
- We observed bosh integration test failures after upgrading
  `delayed_job` in response to known CVEs. The `delayed_job` update
  pulled latest `activesupport` which seems to fail to be required
  correctly for `delayed_job` to use `#extract_options` on an Array.
  e.g. we saw the following error in the test bosh director logs:

```
  ERROR -- Director: NoMethodError - undefined method `extract_options!' for [#<Bosh::Director::Jobs::DBJob:0x00007fd044ef9f90 @job_class=Bosh::Director::Jobs::UpdateRelease, @task_id=1, @args=["/tmp/build/04d13fd0/bosh-src/src/tmp/integration-tests-workspace/pid-9515/sandbox/0000000204", {:rebase=>false, :fix=>false}]>]:Array:
/usr/local/bundle/ruby/3.2.0/gems/delayed_job-4.1.11/lib/delayed/backend/job_preparer.rb:7:in `initialize'
```

- Pinning back to 6.0.x appears to allow delayed_job to call this method
  without issue. Notably we see that zeitwerk (I believe responsible for
  Rails auto-loading behavior) is explicitly shown as a dependency for
  version 6.0.6.1

Signed-off-by: Rajan Agaskar <ragaskar@vmware.com>