Fix issue with installation of local bosh_common gem
This fixes a new failure that has come up during stemcell building:

+ gem install bosh-release --no-rdoc --no-ri -l -w
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: bosh-release requires bosh_common
(~> 1.0000.0); blobstore_client requires bosh_common (~> 1.0000.0)