expose agent_wait_timeout property (#2406)
During a `bosh deploy`, if the BOSH Director is unable to communicate with a 
deployed VM for 600 seconds, the deploy is considered a failure and the the 
BOSH Director will tear down the VM (unless `keep_unreachable_vms` is set to
true).

This commit exposes the 600-second `agent_wait_timeout` property, enabling
to increase it to much greater values, under the belief that although a
VM may take over ten minutes to communicate with the BOSH Director, it'll
be able to perform its other duties in a timely manner. This may be the case
for nested vSphere environments, for example.

Addresses:
```
Error: Timed out pinging VM '...' with agent '...' after 600 seconds
```

Fixes-Bug: #2405