update to latest bosh-cli for ruby 3.2 compability
fixes:

```
Installing CPI:
  Rendering and uploading Jobs:
    Rendering job templates for installation:
      Rendering templates for job 'docker_cpi/4916a5ba95d5ca470817563190100d3dca699bbc7ba44af0bdf9a9ba8aa3b9ad':
        Rendering template src: cpi.erb, dst: bin/cpi:
          Rendering template src: /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/bosh-release-job1187605047/templates/cpi.erb, dst: /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/rendered-jobs223276618/bin/cpi:
            Running ruby to render templates:
              Running command: 'ruby /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-context.json /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/bosh-release-job1187605047/templates/cpi.erb /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/rendered-jobs223276618/bin/cpi', stdout: '', stderr: '/root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:175: warning: Passing safe_level with the 2nd argument of ERB.new is deprecated. Do not use it, and specify other arguments as keyword arguments.
/root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:175: warning: Passing trim_mode with the 3rd argument of ERB.new is deprecated. Use keyword argument like ERB.new(str, trim_mode: ...) instead.
/root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:189:in `rescue in render': Error filling in template '/root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/bosh-release-job1187605047/templates/cpi.erb' for docker_cpi/0 (line unknown: #<NoMethodError: undefined method `taint' for #<Binding:0x00007efec80c1408>>) (RuntimeError)
	from /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:174:in `render'
	from /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:200:in `<main>'
/root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:48:in `get_binding': undefined method `taint' for #<Binding:0x00007efec80c1408> (NoMethodError)

    binding.taint
           ^^^^^^
	from /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:179:in `block in render'
	from /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:178:in `open'
	from /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:178:in `render'
	from /root/.bosh/installations/0d84bfcc-6594-46ee-7bc7-ca7735f85491/tmp/erb-renderer2692608420/erb-render.rb:200:in `<main>'
```

in some tasks that use this image with the ruby 3.2 update.