fix regression in list_disk
typo in 7f61e37f causes 'NoMethodError: undefined method `[]' for nil:NilClass'

Change-Id: I047efc9871981659ad2dc863b7e8f2ab78267ace